#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PACKAGES_CONF="$ROOT_DIR/packages.conf"
DOTFILES_DIR="$ROOT_DIR/dotfiles"
SETTINGS_CONF="$ROOT_DIR/settings.conf"
BACKUP_DIR="$HOME/.bootstrap-backup-$(date +%Y%m%d-%H%M%S)"
PATH="$HOME/.local/bin:$PATH"
export PATH

WITH_RUST=0
WITH_GO=0
WITH_MINICONDA=0
WITH_NODE=0
WITH_CHEAT=0
WITH_XMAKE=0
NO_CHSH=0
APT_SKIPPED_FILE="/tmp/bootstrap-apt-skipped.$$"
VERSION_FAILURES_FILE="/tmp/bootstrap-version-failures.$$"

for arg in "$@"; do
    case "$arg" in
        --with-rust) WITH_RUST=1 ;;
        --with-go) WITH_GO=1 ;;
        --with-miniconda) WITH_MINICONDA=1 ;;
        --with-node) WITH_NODE=1 ;;
        --with-cheat) WITH_CHEAT=1 ;;
        --with-xmake) WITH_XMAKE=1 ;;
        --no-chsh) NO_CHSH=1 ;;
        *)
            echo "Unknown option: $arg" >&2
            exit 2
            ;;
    esac
done

log() {
    printf '\n==> %s\n' "$*"
}

load_settings() {
    [ -f "$SETTINGS_CONF" ] || return
    set -a
    # shellcheck disable=SC1090
    . "$SETTINGS_CONF"
    set +a
}

have() {
    command -v "$1" >/dev/null 2>&1
}

require_sudo() {
    if [ "$(id -u)" -ne 0 ]; then
        SUDO=sudo
    else
        SUDO=
    fi
}

backup_root_file() {
    src="$1"
    [ -e "$src" ] || return
    require_sudo
    backup="${src}.bootstrap-backup-$(date +%Y%m%d-%H%M%S)"
    $SUDO cp "$src" "$backup"
    echo "Backed up $src to $backup"
}

configure_apt_mirror() {
    [ -n "${APT_MIRROR:-}" ] || return
    [ -f /etc/apt/sources.list ] || return

    require_sudo
    codename=$(. /etc/os-release && printf '%s' "${UBUNTU_CODENAME:-${VERSION_CODENAME:-}}")
    if [ -z "$codename" ]; then
        echo "Cannot detect Ubuntu codename; skip apt mirror rewrite."
        return
    fi

    log "Configuring apt mirror: $APT_MIRROR ($codename)"
    backup_root_file /etc/apt/sources.list
    tmp="/tmp/sources.list.$$"
    {
        echo "# Generated by bootstrap-new-machine"
        echo "deb $APT_MIRROR/ $codename main restricted universe multiverse"
        echo "deb $APT_MIRROR/ $codename-updates main restricted universe multiverse"
        echo "deb $APT_MIRROR/ $codename-backports main restricted universe multiverse"
        echo "deb $APT_MIRROR/ $codename-security main restricted universe multiverse"
    } > "$tmp"
    $SUDO cp "$tmp" /etc/apt/sources.list
    rm -f "$tmp"
}

configure_user_registries() {
    if [ -n "${PIP_INDEX_URL:-}" ]; then
        log "Configuring pip index"
        mkdir -p "$HOME/.config/pip"
        {
            echo "[global]"
            echo "index-url = $PIP_INDEX_URL"
            [ -n "${PIP_TRUSTED_HOST:-}" ] && echo "trusted-host = $PIP_TRUSTED_HOST"
        } > "$HOME/.config/pip/pip.conf"
    fi

    if [ -n "${NPM_REGISTRY:-}" ] && have npm; then
        log "Configuring npm registry"
        npm config set registry "$NPM_REGISTRY"
    fi

    if [ -n "${RUSTUP_DIST_SERVER:-}" ] || [ -n "${RUSTUP_UPDATE_ROOT:-}" ] || [ -n "${CARGO_REGISTRIES_CRATES_IO_PROTOCOL:-}" ]; then
        log "Configuring Rust/Cargo environment"
        mkdir -p "$HOME/.cargo"
        env_file="$HOME/.cargo/env.bootstrap"
        : > "$env_file"
        [ -n "${RUSTUP_DIST_SERVER:-}" ] && echo "export RUSTUP_DIST_SERVER='$RUSTUP_DIST_SERVER'" >> "$env_file"
        [ -n "${RUSTUP_UPDATE_ROOT:-}" ] && echo "export RUSTUP_UPDATE_ROOT='$RUSTUP_UPDATE_ROOT'" >> "$env_file"
        [ -n "${CARGO_REGISTRIES_CRATES_IO_PROTOCOL:-}" ] && echo "export CARGO_REGISTRIES_CRATES_IO_PROTOCOL='$CARGO_REGISTRIES_CRATES_IO_PROTOCOL'" >> "$env_file"
        grep -q "env.bootstrap" "$HOME/.zshenv" 2>/dev/null || echo '. "$HOME/.cargo/env.bootstrap" 2>/dev/null || true' >> "$HOME/.zshenv"
    fi

    if [ "${CONDA_USE_TUNA:-0}" = "1" ] && have conda; then
        log "Configuring conda channels"
        conda config --remove-key channels >/dev/null 2>&1 || true
        conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
        conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
        conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
        conda config --set show_channel_urls yes
    fi
}

configure_git_identity() {
    [ -n "${GIT_USER_NAME:-}" ] && git config --global user.name "$GIT_USER_NAME"
    [ -n "${GIT_USER_EMAIL:-}" ] && git config --global user.email "$GIT_USER_EMAIL"
}

read_apt_packages() {
    awk '
        /^[[:space:]]*($|#)/ { next }
        /^\[/ { section=$0; next }
        section ~ /^\[apt:/ { print $1 }
    ' "$PACKAGES_CONF"
}

read_section_items() {
    target="$1"
    awk -v target="[$target]" '
        /^[[:space:]]*($|#)/ { next }
        /^\[/ { section=$0; next }
        section == target { print $1 }
    ' "$PACKAGES_CONF"
}

read_versioned_tools() {
    awk '
        /^[[:space:]]*($|#)/ { next }
        /^\[/ { section=$0; next }
        section == "[external:versioned]" { print $1, $2 }
    ' "$PACKAGES_CONF"
}

tool_version() {
    tool="$1"
    case "$tool" in
        nvim) nvim --version 2>/dev/null | sed -n '1s/.*v//p' ;;
        zellij) zellij --version 2>/dev/null | awk '{print $2}' ;;
        cmake) cmake --version 2>/dev/null | sed -n '1s/.*version //p' ;;
        node) node --version 2>/dev/null | sed 's/^v//' ;;
        go) go version 2>/dev/null | awk '{print $3}' | sed 's/^go//' ;;
        cheat) cheat --version 2>/dev/null ;;
        herdr) herdr --version 2>/dev/null | awk '{print $2}' ;;
        *) "$tool" --version 2>/dev/null | sed -n '1p' ;;
    esac
}

download() {
    url="$1"
    output="$2"
    log "Downloading $url"
    curl -fL "$url" -o "$output"
}

install_versioned_tool() {
    tool="$1"
    version="$2"
    arch=$(uname -m)
    os=$(uname -s)
    opt_dir="$HOME/.local/opt"
    bin_dir="$HOME/.local/bin"
    mkdir -p "$opt_dir" "$bin_dir"

    if [ "$os" != "Linux" ]; then
        echo "$tool $version skipped: only Linux installers are defined"
        return
    fi

    case "$tool:$arch" in
        nvim:x86_64)
            archive="/tmp/nvim-linux-x86_64-$version.tar.gz"
            download "https://github.com/neovim/neovim/releases/download/v${version}/nvim-linux-x86_64.tar.gz" "$archive"
            rm -rf "$opt_dir/nvim-$version"
            mkdir -p "$opt_dir/nvim-$version"
            tar -xzf "$archive" -C "$opt_dir/nvim-$version" --strip-components=1
            ln -sf "$opt_dir/nvim-$version/bin/nvim" "$bin_dir/nvim"
            ;;
        zellij:x86_64)
            archive="/tmp/zellij-x86_64-unknown-linux-musl-$version.tar.gz"
            download "https://github.com/zellij-org/zellij/releases/download/v${version}/zellij-x86_64-unknown-linux-musl.tar.gz" "$archive"
            rm -rf "$opt_dir/zellij-$version"
            mkdir -p "$opt_dir/zellij-$version"
            tar -xzf "$archive" -C "$opt_dir/zellij-$version"
            ln -sf "$opt_dir/zellij-$version/zellij" "$bin_dir/zellij"
            ;;
        cmake:x86_64)
            installer="/tmp/cmake-$version-linux-x86_64.sh"
            download "https://github.com/Kitware/CMake/releases/download/v${version}/cmake-${version}-linux-x86_64.sh" "$installer"
            rm -rf "$opt_dir/cmake-$version"
            mkdir -p "$opt_dir/cmake-$version"
            sh "$installer" --skip-license --prefix="$opt_dir/cmake-$version"
            ln -sf "$opt_dir/cmake-$version/bin/cmake" "$bin_dir/cmake"
            ln -sf "$opt_dir/cmake-$version/bin/ccmake" "$bin_dir/ccmake" 2>/dev/null || true
            ln -sf "$opt_dir/cmake-$version/bin/ctest" "$bin_dir/ctest" 2>/dev/null || true
            ln -sf "$opt_dir/cmake-$version/bin/cpack" "$bin_dir/cpack" 2>/dev/null || true
            ;;
        node:x86_64)
            archive="/tmp/node-v$version-linux-x64.tar.xz"
            download "https://nodejs.org/dist/v${version}/node-v${version}-linux-x64.tar.xz" "$archive"
            rm -rf "$opt_dir/node-$version"
            mkdir -p "$opt_dir/node-$version"
            tar -xJf "$archive" -C "$opt_dir/node-$version" --strip-components=1
            ln -sf "$opt_dir/node-$version/bin/node" "$bin_dir/node"
            ln -sf "$opt_dir/node-$version/bin/npm" "$bin_dir/npm"
            ln -sf "$opt_dir/node-$version/bin/npx" "$bin_dir/npx"
            ;;
        go:x86_64)
            archive="/tmp/go$version.linux-amd64.tar.gz"
            download "https://go.dev/dl/go${version}.linux-amd64.tar.gz" "$archive"
            rm -rf "$opt_dir/go-$version"
            mkdir -p "$opt_dir/go-$version"
            tar -xzf "$archive" -C "$opt_dir/go-$version" --strip-components=1
            ln -sf "$opt_dir/go-$version/bin/go" "$bin_dir/go"
            ln -sf "$opt_dir/go-$version/bin/gofmt" "$bin_dir/gofmt"
            ;;
        cheat:x86_64)
            archive="/tmp/cheat-linux-amd64-$version.gz"
            download "https://github.com/cheat/cheat/releases/download/${version}/cheat-linux-amd64.gz" "$archive"
            gzip -dc "$archive" > "$bin_dir/cheat"
            chmod +x "$bin_dir/cheat"
            ;;
        herdr:x86_64)
            binary="/tmp/herdr-linux-x86_64-$version"
            download "https://github.com/herdrdev/herdr/releases/download/v${version}/herdr-linux-x86_64" "$binary"
            echo "b872ea7e40fa2cb17e857ac9b62b1bf26db7b403c622f5d2f3f5b35f6e9acd28  $binary" | sha256sum -c -
            install -m 0755 "$binary" "$bin_dir/herdr"
            ;;
        herdr:aarch64)
            binary="/tmp/herdr-linux-aarch64-$version"
            download "https://github.com/herdrdev/herdr/releases/download/v${version}/herdr-linux-aarch64" "$binary"
            echo "f647ac66468d9efbc642fe534fb284468f0aea60641606fc008dfc0d82a3ca87  $binary" | sha256sum -c -
            install -m 0755 "$binary" "$bin_dir/herdr"
            ;;
        *)
            echo "$tool $version skipped: no installer rule for architecture $arch"
            ;;
    esac
}

install_versioned_tools() {
    read_versioned_tools | while read -r tool version; do
        [ -n "$tool" ] || continue
        current=$(tool_version "$tool" || true)
        if [ "$current" = "$version" ]; then
            echo "$tool $current already installed (exact match)"
        else
            log "Installing $tool $version"
            install_versioned_tool "$tool" "$version"
        fi
    done
}

install_apt_packages() {
    if ! have apt-get; then
        echo "apt-get not found. This script is tuned for Pop!_OS/Ubuntu." >&2
        exit 1
    fi

    require_sudo
    : > "$APT_SKIPPED_FILE"
    log "Updating apt metadata"
    $SUDO apt-get update

    log "Installing apt packages"
    for package in $(read_apt_packages); do
        if apt-cache show "$package" >/dev/null 2>&1; then
            $SUDO apt-get install -y "$package" || echo "$package install failed" >> "$APT_SKIPPED_FILE"
        else
            echo "$package not found in apt repositories" >> "$APT_SKIPPED_FILE"
        fi
    done
}

backup_and_copy() {
    src="$1"
    dst="$2"
    if [ -e "$dst" ] || [ -L "$dst" ]; then
        mkdir -p "$BACKUP_DIR/$(dirname "${dst#$HOME/}")"
        mv "$dst" "$BACKUP_DIR/${dst#$HOME/}"
    fi
    mkdir -p "$(dirname "$dst")"
    cp -R "$src" "$dst"
}

install_tree() (
    src_dir="$1"
    dst_dir="$2"
    mkdir -p "$dst_dir"

    for child in "$src_dir"/.[!.]* "$src_dir"/*; do
        [ -e "$child" ] || [ -L "$child" ] || continue
        child_name=$(basename "$child")
        child_dst="$dst_dir/$child_name"
        if [ -d "$child" ] && [ ! -L "$child" ]; then
            install_tree "$child" "$child_dst"
        else
            backup_and_copy "$child" "$child_dst"
        fi
    done
)

install_dotfiles() {
    log "Installing dotfiles"
    mkdir -p "$HOME/.config" "$HOME/scripts" "$HOME/.todo"
    touch "$HOME/.todo/TODO.md"

    for item in "$DOTFILES_DIR"/.[!.]* "$DOTFILES_DIR"/*; do
        [ -e "$item" ] || continue
        name=$(basename "$item")
        if [ -d "$item" ] && [ ! -L "$item" ]; then
            install_tree "$item" "$HOME/$name"
        else
            backup_and_copy "$item" "$HOME/$name"
        fi
    done

    chmod +x "$HOME/scripts/show_daily_message.sh" "$HOME/scripts/daily_message.sh" "$HOME/scripts/weather.sh" 2>/dev/null || true
    if [ -f "$HOME/.config/neomutt/private.muttrc.example" ] && [ ! -f "$HOME/.config/neomutt/private.muttrc" ]; then
        cp "$HOME/.config/neomutt/private.muttrc.example" "$HOME/.config/neomutt/private.muttrc"
        chmod 600 "$HOME/.config/neomutt/private.muttrc"
        echo "Created ~/.config/neomutt/private.muttrc from template; edit credentials before using neomutt."
    fi
    if [ -d "$BACKUP_DIR" ]; then
        echo "Existing files were backed up to: $BACKUP_DIR"
    fi
}

install_zinit_now() {
    if [ ! -f "$HOME/.local/share/zinit/zinit.git/zinit.zsh" ]; then
        log "Installing zinit"
        mkdir -p "$HOME/.local/share/zinit"
        git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git"
    fi
}

install_optional_tools() {
    for tool in $(read_section_items "external:optional"); do
        case "$tool" in
            rustup) WITH_RUST=1 ;;
            go) WITH_GO=1 ;;
            miniconda) WITH_MINICONDA=1 ;;
            node) WITH_NODE=1 ;;
            cheat) WITH_CHEAT=1 ;;
            xmake) WITH_XMAKE=1 ;;
            *) echo "Unknown external tool in packages.conf: $tool" ;;
        esac
    done

    if [ "$WITH_RUST" -eq 1 ] && ! have rustup; then
        log "Installing rustup"
        curl --proto '=https' --tlsv1.2 -fsSL https://sh.rustup.rs | sh -s -- -y
        if [ -f "$HOME/.cargo/env" ]; then
            # shellcheck disable=SC1090
            . "$HOME/.cargo/env"
        fi
    fi

    if [ "$WITH_GO" -eq 1 ] && ! have go; then
        log "Installing Go from apt"
        require_sudo
        if apt-cache show golang-go >/dev/null 2>&1; then
            $SUDO apt-get install -y golang-go
        else
            echo "golang-go not found in apt repositories; install Go manually if you need a fixed upstream version."
        fi
    fi

    if [ "$WITH_MINICONDA" -eq 1 ] && [ ! -x "$HOME/miniconda3/bin/conda" ]; then
        log "Installing Miniconda"
        tmp="/tmp/miniconda.sh"
        curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o "$tmp"
        sh "$tmp" -b -p "$HOME/miniconda3"
    fi

    if [ "$WITH_NODE" -eq 1 ] && ! have node; then
        log "Node requested; prefer [external:versioned] node to avoid old apt versions."
    fi

    if [ "$WITH_CHEAT" -eq 1 ] && ! have cheat; then
        if have go; then
            log "Installing cheat with go install"
            go install github.com/cheat/cheat/cmd/cheat@latest
        else
            log "cheat requested but Go is not installed"
            echo "Uncomment go or install Go first, then rerun with --with-cheat."
        fi
    fi

    if [ "$WITH_XMAKE" -eq 1 ] && ! have xmake; then
        log "Installing xmake"
        curl -fsSL https://xmake.io/shget.text | bash
    fi
}

verify_versions() {
    : > "$VERSION_FAILURES_FILE"
    log "Checking versioned tools"
    read_versioned_tools | while read -r tool version; do
        [ -n "$tool" ] || continue
        current=$(tool_version "$tool" || true)
        if [ -z "$current" ]; then
            message="$tool missing; expected exactly $version"
            echo "$message"
            echo "$message" >> "$VERSION_FAILURES_FILE"
        elif [ "$current" = "$version" ]; then
            echo "$tool $current OK (exact match)"
        else
            message="$tool $current does not match expected $version"
            echo "$message"
            echo "$message" >> "$VERSION_FAILURES_FILE"
        fi
    done

    if [ -s "$VERSION_FAILURES_FILE" ]; then
        return 1
    fi
    rm -f "$VERSION_FAILURES_FILE"
}

install_npm_globals() {
    packages=$(read_section_items "npm:global" | tr '\n' ' ')
    [ -n "$packages" ] || return

    if ! have npm; then
        echo "npm global packages selected, but npm is not installed. Uncomment node or install npm first."
        return
    fi

    log "Installing npm global packages"
    # shellcheck disable=SC2086
    npm install -g $packages
}

install_cargo_globals() {
    packages=$(read_section_items "cargo:global" | tr '\n' ' ')
    [ -n "$packages" ] || return

    if ! have cargo; then
        echo "cargo packages selected, but cargo is not installed. Uncomment rustup or install Rust first."
        return
    fi

    log "Installing cargo packages"
    for package in $packages; do
        cargo install "$package" || echo "cargo install failed: $package"
    done
}

initialize_dotfile_tools() {
    if [ "${NVIM_LAZY_SYNC:-1}" = "1" ] && have nvim; then
        log "Syncing Neovim plugins"
        nvim --headless "+Lazy! sync" +qa || echo "Neovim Lazy sync failed; open nvim and run :Lazy sync manually."
    fi
}

print_skipped() {
    if [ -s "$APT_SKIPPED_FILE" ]; then
        log "Apt packages skipped or failed"
        cat "$APT_SKIPPED_FILE"
    fi
    rm -f "$APT_SKIPPED_FILE"
}

set_default_shell() {
    if [ "$NO_CHSH" -eq 1 ]; then
        return
    fi
    if have zsh && [ "${SHELL:-}" != "$(command -v zsh)" ]; then
        log "Changing default shell to zsh"
        chsh -s "$(command -v zsh)" || echo "chsh failed; run manually: chsh -s $(command -v zsh)"
    fi
}

main() {
    load_settings
    configure_apt_mirror
    install_apt_packages
    install_dotfiles
    configure_user_registries
    configure_git_identity
    install_zinit_now
    install_versioned_tools
    install_optional_tools
    configure_user_registries
    install_npm_globals
    install_cargo_globals
    initialize_dotfile_tools
    set_default_shell
    if ! verify_versions; then
        print_skipped
        log "Finished with version check failures"
        rm -f "$VERSION_FAILURES_FILE"
        exit 1
    fi
    print_skipped
    log "Done. Start a new terminal, or run: exec zsh"
}

main "$@"
